### ISSUE TITLE
API-create-party-info service call is successful even without providing mandatory fields

### ISSUE THREAD

**Issue by satyajit-sureit** [Sureit/ppms#77]
Steps to Reproduce:

![image](https://user-images.githubusercontent.com/38319427/38732224-0ce79706-3f3b-11e8-9acd-9cc2b2fdce8a.png)

**Comment by Sudhir-perf** [comment]
please fixed now...

**Comment by satyajit-sureit** [comment]
retested the bug, it is working fine now
