### ISSUE TITLE
get-states Webservice: Request is passing even when incorrect countryId is given.

### ISSUE THREAD

**Issue by Sudhir-perf** [Sureit/ppms#99]
Request is passing even when "CountryId/0" is given, however DB shows no record/document with countryId:0
Below screenshot where countries start with Id:1, check the entire list of countries no list of countryId:0

![image](https://user-images.githubusercontent.com/36834911/38820584-e9405760-41bb-11e8-8f1d-4334dc9fe328.png)

**Comment by Mo7an** [comment]
**please do the following changes in the database**:- 
remove the document with the **country_id : 0** 
**query:-**  db.getCollection('States').remove({country_id:0}) 
and insert a document with the **country_id : 124**  and the query for that
**query:-** db.getCollection("States").insertOne({
   "_id" : 4121,
   "name" : "ajdabiya",
   "country_id" : 124
})

**Comment by Sudhir-perf** [comment]
Checked Countries Collections. working fine.Closing this issue as of now....

**Comment by Sudhir-perf** [comment]
checked Both countries and states collection, working fine. Closing the issue as of now...
